name: Publish Docker image to GitHub Package Registry
on:
  release:
    types: [published]
jobs:
  build:
    env:
      IMAGE_NAME: pushpull
    runs-on: ubuntu-latest
    steps:
    - name: Copy Files
      uses: actions/checkout@v2
    - name: Get version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build image
      run: docker build -f Dockerfile --no-cache -t $IMAGE_NAME .
    - name: Tag image
      run: |
        docker tag $IMAGE_NAME "docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:latest"
        docker tag $IMAGE_NAME "docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:${{ steps.vars.outputs.tag }}"
    - name: Publish image
      run: |
        docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:latest"
        docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:${{ steps.vars.outputs.tag }}"
